apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${secret_provider_class_name}
  namespace: nebuly
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${aks_managed_identity_id}
    keyvaultName: ${key_vault_name}
    tenantId: ${tenant_id}

    objects: |
      array:
        - |
          objectName: ${secret_name_db_username}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_db_password}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_openai_api_key}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_jwt_signing_key}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_azure_client_id}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_azure_client_secret}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_nebuly_client_id}
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ${secret_name_nebuly_client_secret}
          objectType: secret              
          objectVersion: ""

  secretObjects:
    - data:
        - key: ${k8s_secret_key_db_password}
          objectName: ${secret_name_db_password}
        - key: ${k8s_secret_key_db_username}
          objectName: ${secret_name_db_username}
        - key: ${k8s_secret_key_openai_api_key}
          objectName: ${secret_name_openai_api_key}
        - key: ${k8s_secret_key_azure_client_id}
          objectName: ${secret_name_azure_client_id}
        - key: ${k8s_secret_key_azure_client_secret}
          objectName: ${secret_name_azure_client_secret}
        - key: ${k8s_secret_key_jwt_signing_key}
          objectName: ${secret_name_jwt_signing_key}
        - key: ${k8s_secret_key_nebuly_client_id}
          objectName: ${secret_name_nebuly_client_id}
        - key: ${k8s_secret_key_nebuly_client_secret}
          objectName: ${secret_name_nebuly_client_secret}
      secretName: ${secret_provider_class_secret_name}
      type: Opaque
